- platform: template
  sensors:
    iemand_thuis:
      friendly_name: "Iemand thuis"
      value_template: >
        {% if (is_state('input_boolean.force_not_home', 'on')) %}
          false
        {% elif (is_state('input_boolean.guest_mode', 'on')) %}
          true
        {% elif (is_state('binary_sensor.luuk_home', 'on')) %}
          true
        {% elif (is_state('device_tracker.phone_hans', 'home')) %}
          true
        {% elif (is_state('device_tracker.iphonevanelly', 'home')) %}
          true
        {% else %} 
          false
        {% endif %}
    luuk_home:
      friendly_name: Luuk
      device_class: presence
      value_template: >
        {% if (is_state('device_tracker.iphone_van_luuk', 'home')) %}
          True
        {% elif (is_state('device_tracker.iphone_van_luuk_nmap', 'home')) %}
          True
        {% else %} 
          False
        {% endif %}
        
- platform: template
  sensors:
    dark_outside:
      friendly_name: "Dark outside"
      value_template: >
        {% if (states.sun.sun.attributes.elevation | int < 20) %}true
        {% elif ( (states.sun.sun.attributes.elevation | int < 25) and (states.sensor.dark_sky_cloud_coverage.state | int > 40)) %}true
        {% elif ( (states.sun.sun.attributes.elevation | int < 30) and (states.sensor.dark_sky_cloud_coverage.state | int > 70)) %}true
        {% elif (states.sensor.dark_sky_cloud_coverage.state | int > 99) %}true
        {% else %}false
        {% endif %}
- platform: template
  sensors:
    harmony_tv_activity:
      friendly_name: 'Harmony Hub TV activity'
      value_template: >-
        {%- if states.media_player.woonkamer.state == "playing"
            and (
              states.media_player.woonkamer.attributes.app_name == "DS video"
              or states.media_player.woonkamer.attributes.media_content_type == "tvshow"
              or states.media_player.woonkamer.attributes.media_content_type == "video"
              or states.media_player.woonkamer.attributes.media_content_type == "episode"
            )-%}
        True
        {%- else -%}
        False
        {%- endif %}
#         value_template: >-
#           {%- if states.remote.harmony_hub.attributes.current_activity == "Watch TV"
#               or states.remote.harmony_hub.attributes.current_activity == "Watch Chromecast"
#               or states.remote.harmony_hub.attributes.current_activity == "PlayStation"
#               or states.remote.harmony_hub.attributes.current_activity == "Watch Smart TV" -%}
#           True
#           {%- else -%}
#           False
#           {%- endif %}
- platform: template
  sensors:
    spotify_playing_to_receiver:
      friendly_name: 'Spotify playing to receiver'
      value_template: >-
        {%- if (states.media_player.spotify.state == "playing" or states.media_player.yamaha_receiver.state == "playing")
            and states.media_player.spotify.attributes.source == "Huiskamer" -%}
        True
        {%- else -%}
        False
        {%- endif %}
- platform: template
  sensors:
    spotify_playing_to_kitchen:
      friendly_name: 'Spotify playing in kitchen'
      value_template: >-
        {%- if (states.media_player.spotify.state == "playing" or states.media_player.keuken.state == "playing")
            and states.media_player.spotify.attributes.source == "Keuken" -%}
        True
        {%- else -%}
        False
        {%- endif %}
  