homeassistant:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 7
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: "tele/hass1/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/hass1/LWT"
    payload: "Offline"
    qos: 1
    retain: true

input_boolean: !include input_booleans.yaml

tado:
  username: !secret tado_username
  password: !secret tado_password

media_player:
  - platform: yamaha
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

frontend:

ios:

config:

http:
  api_password: !secret http_api_password
  ip_ban_enabled: True
  login_attempts_threshold: !secret http_login_attempts_threshold

updater:

discovery:
  ignore:
    - harmony

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

history:
  exclude:
    domains:
      - automation
      - updater
      - script

logbook:

sun:

binary_sensor:
  - platform: template
    sensors:
      dark_outside:
        friendly_name: "Dark outside"
        value_template: >
          {% if (states.sun.sun.attributes.elevation | int < 30) %}true
          {% elif ( (states.sun.sun.attributes.elevation | int < 40) and (states.sensor.dark_sky_cloud_coverage.state | int > 50)) %}true
          {% elif (states.sensor.dark_sky_cloud_coverage.state | int > 90) %}true
          {% else %}false
          {% endif %}
        entity_id:
          - sun.sun
          - sensor.dark_sky_cloud_coverage
  - platform: template
    sensors:
      harmony_tv_activity:
        friendly_name: 'Harmony Hub TV activity'
        value_template: >-
          {%- if states.media_player.woonkamer.state == "playing" -%}
          True
          {%- else -%}
          False
          {%- endif %}
#         value_template: >-
#           {%- if states.remote.harmony_hub.attributes.current_activity == "Watch TV"
#               or states.remote.harmony_hub.attributes.current_activity == "Watch Chromecast"
#               or states.remote.harmony_hub.attributes.current_activity == "PlayStation"
#               or states.remote.harmony_hub.attributes.current_activity == "Watch Smart TV" -%}
#           True
#           {%- else -%}
#           False
#           {%- endif %}
        entity_id:
          - remote.harmony_hub
          - media_player.woonkamer
  - platform: mqtt
    name: "Bewegingssensor keuken"
    state_topic: "cmnd/sonoff_keuken_motion_sensor/POWER1"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    device_class: "motion"

sensor:
  - platform: template
    sensors:
      solar_angle:
        value_template: '{{ "%+.1f"|format(states.sun.sun.attributes.elevation) }}'
        friendly_name: 'Sun Angle'
        unit_of_measurement: 'degrees'
  - platform: buienradar
    monitored_conditions:
      - humidity
      - temperature
      - windspeed
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - cloud_cover
  - platform: mqtt
    name: "Wasmachine verbruik vandaag"
    state_topic: "tele/wasmachine/ENERGY"
    value_template: "{{ value_json.Today }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Wasmachine actueel verbruik"
    state_topic: "tele/wasmachine/ENERGY"
    value_template: "{{ value_json.Power }}"
    unit_of_measurement: "W"

switch:
  - platform: mqtt
    name: "Wasmachine"
    state_topic: "stat/wasmachine/POWER"
    command_topic: "cmnd/wasmachine/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

# Text to speech
# tts:
#   platform: google

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
  - platform: tado
    username: !secret tado_username
    password: !secret tado_password
    home_id: !secret tado_home_id

zone:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  radius: 50
  icon: mdi:home

remote:
  - platform: harmony
    name: "Harmony Hub"
    host: 10.0.0.71
    scan_interval: 10

light: !include lights.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml