homeassistant:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 7
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages
  customize: !include customize.yaml
  customize_glob:
    "sensor.miflora_*":
      hidden: true
    "sensor.ipad_air_2_*":
      hidden: true
    "sensor.iphone_*":
      hidden: true

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: "tele/hass1/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/hass1/LWT"
    payload: "Offline"
    qos: 1
    retain: true

tado:
  username: !secret tado_username
  password: !secret tado_password

media_player:
  - platform: yamaha
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

frontend:

ios: !include ios.yaml

config:

http:
  api_password: !secret http_api_password
  ip_ban_enabled: true
  login_attempts_threshold: !secret http_login_attempts_threshold

discovery:
  ignore:
    - harmony
    - yeelight

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_aqara_mac
      key: !secret xiaomi_aqara_key

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token

emulated_hue:
  exposed_domains:
    - light

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

recorder:
  db_url: !secret db_url
  purge_interval: 1
  purge_keep_days: 14

history:
  exclude:
    domains:
      - automation
      - updater
      - script
      - group

logbook:
  exclude:
    entities:
      - group.system_group
      - switch.cpu_fan
      - automation.cpu_fan_on
      - automation.cpu_fan_off

panel_iframe:
  sonarr:
    title: 'Sonarr'
    icon: mdi:television
    url: !secret sonarr_url
  tado:
    title: "tado⁠°"
    icon: mdi:thermometer
    url: "https://my.tado.com/"

sun:

# Text to speech
# tts:
#   platform: google

device_tracker:
  - platform: nmap_tracker
    hosts: 10.0.0.1/24
    track_new_devices: false
    interval_seconds: 30
    home_interval: 5
    consider_home: 300
  - platform: tado
    username: !secret tado_username
    password: !secret tado_password
    home_id: !secret tado_home_id

zone:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  radius: 80
  icon: mdi:home

remote:
  - platform: harmony
    name: "Harmony Hub"
    host: 10.0.0.71
    scan_interval: 10

influxdb:
  host: !secret influxdb_host

input_boolean: !include input_booleans.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
