homeassistant:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 7
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages
  customize: !include customize.yaml
  customize_glob:
    "sensor.miflora_*":
      hidden: true
    "sensor.ipad_air_2_*":
      hidden: true
    "sensor.iphone_*":
      hidden: true

tado:
  username: !secret tado_username
  password: !secret tado_password

media_player:
  - platform: yamaha
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

yeelight:
  devices:
    10.0.0.45:
      name: Zithoek
    10.0.0.72:
      name: Keuken
    10.0.0.242:
      name: Eettafel
    10.0.0.108:
      name: Woonkamer plant
    10.0.0.80:
      name: Woonkamer schemerlamp
    10.0.0.59:
      name: Lamp kledingkast
    10.0.0.120:
      name: Slaapkamer

system_health:

speedtestdotnet:

frontend:

ios: !include ios.yaml

mobile_app:

config:

webhook:

zigbee2mqtt_networkmap:

http:
  ip_ban_enabled: true
  login_attempts_threshold: !secret http_login_attempts_threshold
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies

discovery:
  ignore:
    - harmony
    - igd
    - yeelight

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key

emulated_hue:
  exposed_domains:
    - light

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

recorder:
  db_url: !secret db_url
  purge_interval: 1
  purge_keep_days: 7

history:
  exclude:
    entities:
      - sensor.time
      - sensor.memory_free
      - sensor.memory_use
      - sensor.processor_use
    domains:
      - automation
      - updater
      - script
      - group
      - sun

logbook:
  exclude:
    entities:
      - automation.vacuum_map_refresh
      - sensor.mqtt_plant_druivenstruik_battery
      - sensor.mqtt_plant_druivenstruik_brightness
      - sensor.mqtt_plant_druivenstruik_conductivity
      - sensor.mqtt_plant_druivenstruik_moisture
      - sensor.mqtt_plant_druivenstruik_temperature
      - sensor.mqtt_plant_koelkast_battery
      - sensor.mqtt_plant_koelkast_brightness
      - sensor.mqtt_plant_koelkast_conductivity
      - sensor.mqtt_plant_koelkast_moisture
      - sensor.mqtt_plant_koelkast_temperature
      - sensor.mqtt_plant_woonkamer_hoek_battery
      - sensor.mqtt_plant_woonkamer_hoek_brightness
      - sensor.mqtt_plant_woonkamer_hoek_conductivity
      - sensor.mqtt_plant_woonkamer_hoek_moisture
      - sensor.mqtt_plant_woonkamer_hoek_temperature
      - sensor.vacuum_map

panel_iframe:
  sonarr:
    title: 'Sonarr'
    icon: mdi:television
    url: !secret sonarr_url
  tado:
    title: "tado⁠°"
    icon: mdi:thermometer
    url: "https://my.tado.com/"
  networkmap:
    title: 'Zigbee Map'
    url: '/local/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

sun:

# Text to speech
# tts:
#   platform: google

person:

device_tracker:
  - platform: synology_srm
    host: 10.0.0.1
    username: !secret synology_router_username
    password: !secret synology_router_password
    new_device_defaults:
      track_new_devices: false
  - platform: tado
    username: !secret tado_username
    password: !secret tado_password
    home_id: !secret tado_home_id

zone:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  radius: 80
  icon: mdi:home

remote:
  - platform: harmony
    name: "Harmony Hub"
    host: 10.0.0.71
    scan_interval: 10

influxdb:
  host: !secret influxdb_host
  max_retries: 5

input_boolean: !include input_booleans.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
group: !include groups.yaml
