- platform: mqtt
  name: "Spotjes keuken links"
  state_topic: "stat/sonoff_keuken_spots_links/POWER1"
  command_topic: "cmnd/sonoff_keuken_spots_links/POWER1"
  availability_topic: "tele/sonoff_keuken_spots_links/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Spotjes keuken rechts"
  state_topic: "stat/sonoff_keuken_spots_rechts/POWER1"
  command_topic: "cmnd/sonoff_keuken_spots_rechts/POWER1"
  availability_topic: "tele/sonoff_keuken_spots_rechts/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Lamp hal achter"
  state_topic: "stat/sonoff_hal_achter/POWER1"
  command_topic: "cmnd/sonoff_hal_achter/POWER1"
  availability_topic: "tele/sonoff_hal_achter/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Lamp hal voordeur"
  state_topic: "stat/sonoff_hal_voordeur/POWER1"
  command_topic: "cmnd/sonoff_hal_voordeur/POWER1"
  availability_topic: "tele/sonoff_hal_voordeur/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: switch
  name: Plafondlamp badkamer
  entity_id: switch.qubino_zmnhbdx_flush_2_relays_switch_2
- platform: switch
  name: Wastafellamp badkamer
  entity_id: switch.qubino_zmnhbdx_flush_2_relays_switch_3