- platform: yeelight
  devices:
    10.0.0.45:
      name: Zithoek
      use_music_mode: True
    10.0.0.72:
      name: Keuken
      use_music_mode: True
    10.0.0.80:
      name: Eettafel
      use_music_mode: True
    10.0.0.108:
      name: Schemerlamp
      use_music_mode: True
- platform: mqtt
  name: "Spotjes keuken links"
  state_topic: "stat/sonoff_keuken_spots_links/POWER"
  command_topic: "cmnd/sonoff_keuken_spots_links/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Spotjes keuken rechts"
  state_topic: "stat/sonoff_keuken_spots_rechts/POWER"
  command_topic: "cmnd/sonoff_keuken_spots_rechts/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true