- platform: yeelight
  devices:
    10.0.0.45:
      name: Zithoek
    10.0.0.72:
      name: Keuken
    10.0.0.80:
      name: Eettafel
    10.0.0.108:
      name: Woonkamer plant
- platform: mqtt
  name: "Spotjes keuken links"
  state_topic: "stat/sonoff_keuken_spots_links/POWER"
  command_topic: "cmnd/sonoff_keuken_spots_links/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Spotjes keuken rechts"
  state_topic: "stat/sonoff_keuken_spots_rechts/POWER"
  command_topic: "cmnd/sonoff_keuken_spots_rechts/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true