- platform: buienradar
  monitored_conditions:
    - temperature
    - humidity
    - windspeed
    - windgust
    - precipitation
    - irradiance
    - windforce_1d
    - temperature_1d

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - cloud_cover

- platform: mold_indicator
  name: mold_sensor_bathroom
  indoor_temp_sensor: sensor.temperature_158d0001b91ff4
  indoor_humidity_sensor: sensor.humidity_158d0001b91ff4
  outdoor_temp_sensor: sensor.temperature_158d0001b95352
  calibration_factor: 3.0

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free

- platform: cert_expiry
  host: !secret ha_hostname
    
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

