- platform: buienradar
  monitored_conditions:
    - humidity
    - temperature
    - windspeed

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - cloud_cover

- platform: mqtt
  name: "Wasmachine verbruik vandaag"
  state_topic: "tele/wasmachine/ENERGY"
  availability_topic: "tele/wasmachine/LWT"
  value_template: "{{ value_json.Today }}"
  unit_of_measurement: "kWh"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wasmachine actueel verbruik"
  state_topic: "tele/wasmachine/ENERGY"
  availability_topic: "tele/wasmachine/LWT"
  value_template: "{{ value_json.Power }}"
  unit_of_measurement: "W"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: miflora
  hidden: true
  mac: 'C4:7C:8D:63:75:0A'
  name: miflora
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: template
  sensors:
    ventilation_current_mode:
      value_template: >
        {% if (is_state('switch.qubino_zmnhbdx_flush_2_relays_switch_2', 'on')) %}
          3.0
        {% elif (is_state('switch.qubino_zmnhbdx_flush_2_relays_switch_3', 'on')) %}
          2.0
        {% else %} 
          1.0
        {% endif %}

- platform: mold_indicator
  name: mold_sensor_bathroom
  indoor_temp_sensor: sensor.temperature_158d0001b91ff4
  indoor_humidity_sensor: sensor.humidity_158d0001b91ff4
  outdoor_temp_sensor: sensor.slaapkamer_temperature
  calibration_factor: 3.0

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

