- platform: mqtt
  name: "Wasmachine"
  state_topic: "stat/wasmachine/POWER"
  command_topic: "cmnd/wasmachine/POWER"
  availability_topic: "tele/wasmachine/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true