script:
  send_battery_low_notification:
    sequence:
      - service: notify.mobile_app_iphone_van_luuk
        data_template:
          title: "Batterij bijna leeg"
          message: 'De batterij van {{ device_name }} is bijna leeg ({{ battery_left | int }}%).'
          data:
            push:
              thread-id: "system"
      - service: persistent_notification.create
        data_template:
          title: "Batterij bijna leeg"
          message: 'De batterij van **{{ device_name }}** is bijna leeg ({{ battery_left | int }}%).'
          notification_id: "{{ device_name}}"

automation:
  - id: battery_low_notification
    alias: "Batterij bijna leeg notificatie"
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.0x00158d00015766fb_battery
          - sensor.0x00158d000157670b_battery
          - sensor.0x00158d00015f2255_battery
          - sensor.0x00158d00016c22e6_battery
          - sensor.0x00158d000183f47d_battery
          - sensor.0x00158d0001ab31bc_battery
          - sensor.0x00158d0001ad6a52_battery
          - sensor.0x00158d0001b147ce_battery
          - sensor.0x00158d0001b7930d_battery
          - sensor.0x00158d0001b91ff4_battery
          - sensor.0x00158d0001b95352_battery
          - sensor.0x00158d0001bf46e8_battery
          - sensor.0x00158d0001d62bf9_battery
          - sensor.0x00158d0001d645d5_battery
          - sensor.0x00158d0001db9792_battery
          - sensor.0x00158d0001e470dc_battery
          - sensor.0x00158d0001e481df_battery
          - sensor.0x00158d0001e48a17_battery
          - sensor.0x00158d0001e544b9_battery
          - sensor.0x00158d000224fbf6_battery
          - sensor.0x00158d000248cc5a_battery
          - sensor.0x00158d000248ef10_battery
          - sensor.0x00158d0002af965a_battery
          - sensor.0x00158d0002e9873b_battery
          - sensor.0x00158d0003021728_battery
          - sensor.0x00158d00030aa32c_battery
          - sensor.0x00158d00033a9490_battery
          - sensor.mqtt_plant_druivenstruik_battery
          - sensor.mqtt_plant_koelkast_battery
          - sensor.mqtt_plant_woonkamer_hoek_battery
          - sensor.mqtt_plant_woonkamer_tv_battery
        above: 0
        below: 20
        for:
          hours: 12
    action:
      - service: script.send_battery_low_notification
        data_template:
          device_name: "{{ trigger.to_state.name }}"
          battery_left: "{{ trigger.to_state.state }}"