switch:
  - platform: rpi_gpio
    ports:
      18: CPU Fan

automation:
  - id: cpu_fan_on
    alias: "CPU Fan on"
    hide_entity: True
    trigger:
      platform: numeric_state
      entity_id: sensor.cpu_temperature
      above: 55
    action:
      - service: switch.turn_on
        entity_id: switch.cpu_fan
        
  - id: cpu_fan_off
    alias: "CPU Fan off"
    hide_entity: True
    trigger:
      platform: numeric_state
      entity_id: sensor.cpu_temperature
      below: 55
    action:
      - service: switch.turn_off
        entity_id: switch.cpu_fan