homeassistant:
  customize:
    binary_sensor.kaku_doorbell:
      hidden: true
    input_boolean.doorbell_state:
      hidden: true

input_boolean:
  doorbell_state:
    initial: off

binary_sensor:
  - platform: template
    sensors:
      doorbell_ringing:
        friendly_name: "Deurbel"
        value_template: "{{ is_state('input_boolean.doorbell_state', 'on') }}"
        icon_template: >-
          {%- if is_state('input_boolean.doorbell_state', 'on') -%}
            mdi:bell-ring
          {%- else -%}
            mdi:bell
          {%- endif %}
  
  - platform: mqtt
    name: "KAKU Doorbell"
    state_topic: "home/RF2toMQTT/CODE_8318190/UNIT_0/GROUP_1/#"
    payload_on: "1"
    payload_off: "0"
    availability_topic: "home/OpenMQTTGateway/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

automation:
  - id: doorbell_state_on
    alias: Deurbel ingedrukt
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kaku_doorbell
        to: "on"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.doorbell_state
  
  - id: doorbell_state_reset
    alias: Deurbel reset
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.doorbell_state
        to: "on"
        for:
          seconds: 10
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.doorbell_state
      - service: mqtt.publish
        data:
          topic: "home/RF2toMQTT/CODE_8318190/UNIT_0/GROUP_1/PERIOD_253"
          payload: "0"
  
  - id: doorbell_notification
    alias: "Doorbell notification"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.doorbell_state
        to: "on"
    action:
      - service: notify.mobile_app_iphone_van_luuk
        data:
          title: "Deurbel:"
          message: "Er wordt aangebeld!"
          data:
            push:
              thread-id: "front_door"
            apns_headers:
              'apns-collapse-id': 'doorbell-notification'
