binary_sensor:
  - platform: template
    sensors:
      mailbox:
        friendly_name: "Brievenbus"
        value_template: '{{ is_state("binary_sensor.0x00158d0001b147ce", "on") }}'
        device_class: opening
        delay_off:
          seconds: 30
        

automation:
  - id: mailbox_notification
    alias: "Brievenbusnotificatie"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.mailbox
        to: "on"
    action:
      - service: notify.ios_iphone_van_luuk
        data:
          title: "Brievenbus:"
          message: "Er is post!"