group:
  vacuum_cleaners:
    name: Stofzuigers
    icon: mdi:robot-vacuum
    control: hidden
    entities:
      - vacuum.stofzuiger_woonkamer
      - vacuum.stofzuiger_boven
      - script.move_vacuum_cleaner_for_service
      - camera.vacuum_map

vacuum:
  - platform: xiaomi_miio
    name: Stofzuiger boven
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token

  - platform: template
    vacuums:
      stofzuiger_woonkamer:
        friendly_name: Stofzuiger woonkamer
        value_template: >-
          {%- if states('binary_sensor.vacuum_moving') == 'on' -%}
            cleaning
          {%- else -%}
            idle
          {%- endif %}
        start:
          # Wake up the vacuum
          - service: remote.send_command
            data:
              entity_id: remote.harmony_hub
              command: Clean
              device: 45085387
          - delay:
              seconds: 4
          # Start cleaning
          - service: remote.send_command
            data:
              entity_id: remote.harmony_hub
              command: Clean
              device: 45085387
        return_to_base:
          - service: remote.send_command
            data:
              entity_id: remote.harmony_hub
              command: Home
              device: 45085387
        clean_spot:
          - service: remote.send_command
            data:
              entity_id: remote.harmony_hub
              command: SpotCleaning
              device: 45085387

sensor:
  - platform: rest
    name: Vacuum map
    resource: http://10.0.0.74/api/remote/map?scale=5&border=0
    value_template: 'http://10.0.0.74{{value_json.mapsrc}}'
    scan_interval: 300
binary_sensor:
  - platform: template
    sensors:
      vacuum_moving:
        value_template: '{{states("sensor.0x00158d0002af965a") not in ("unknown", "") }}'
        delay_off:
          seconds: 90

camera:
  - platform: generic
    name: Vacuum map
    still_image_url: '{{states("sensor.vacuum_map")}}'
    content_type: "image/png"
    limit_refetch_to_url_change: true

automation:
  - id: vacuum_cleaner_schedule
    initial_state: 'on'
    alias: "Stofzuigen"
    trigger:
      platform: state
      entity_id: binary_sensor.iemand_thuis
      to: 'off'
    condition:
      - condition: time
        after: "07:00:00"
        before: "12:00:00"
        weekday:
          - mon
          - fri
    action:
      - service: vacuum.start
        entity_id: vacuum.stofzuiger_woonkamer
      - service: vacuum.start
        entity_id: vacuum.stofzuiger_boven
      - service: notify.ios_iphone_van_luuk
        data:
          message: "Stofzuigers gestart"
          data:
            attachment:
              content-type: "png"
            push:
              category: camera
              thread-id: "huishoudelijk"
            entity_id: camera.vacuum_map
  
  - alias: Stofzuigen klaar notificatie
    id: vacuum_done_notification
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: vacuum.stofzuiger_boven
        from: 'cleaning'
        to: 'returning'
      - platform: state
        entity_id: vacuum.stofzuiger_boven
        from: 'cleaning'
        to: 'docked'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ states.vacuum.stofzuiger_boven.attributes.cleaning_time | int > 5 }}'
    action:
      - service: notify.ios_iphone_van_luuk
        data:
          message: "Stofzuigen klaar!"
          data:
            attachment:
              content-type: "png"
            push:
              category: camera
              thread-id: "huishoudelijk"
            entity_id: camera.vacuum_map
  
  - alias: Stofzuigen fout notificatie
    id: vacuum_error_notification
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: vacuum.stofzuiger_boven
        to: 'error'
    action:
      - service: notify.ios_iphone_van_luuk
        data:
          title: '{{ states.vacuum.stofzuiger_boven.attributes.friendly_name }} vastgelopen!'
          message: 'Foutmelding: {{ states.vacuum.stofzuiger_boven.attributes.error }}'
          data:
            attachment:
              content-type: "png"
            push:
              category: camera
              thread-id: "huishoudelijk"
            entity_id: camera.vacuum_map

  - alias: Vacuum map refresh
    id: vacuum_map_refresh
    initial_state: 'on'
    trigger:
      platform: time_pattern
      seconds: '/5'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: vacuum.stofzuiger_boven
          state: 'cleaning'
        - condition: state
          entity_id: vacuum.stofzuiger_boven
          state: 'returning'
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.vacuum_map

script:
  move_vacuum_cleaner_for_service:
    alias: Stofzuiger verplaatsen voor onderhoud
    sequence:
    - service: vacuum.xiaomi_remote_control_start
      data:
        entity_id: vacuum.stofzuiger_boven
    - delay: 00:00:10
    - service: vacuum.xiaomi_remote_control_move
      data:
        entity_id: vacuum.stofzuiger_boven
        duration: 3000
        rotation: 0
        velocity: 0.2
    - delay: 00:00:03
    - service: vacuum.xiaomi_remote_control_move
      data:
        entity_id: vacuum.stofzuiger_boven
        duration: 80
        rotation: 30
        velocity: 0.1
    - delay: 00:00:02
    - service: vacuum.xiaomi_remote_control_move
      data:
        entity_id: vacuum.stofzuiger_boven
        duration: 3000
        rotation: 0
        velocity: 0.2
    - delay: 00:00:03
    - service: vacuum.xiaomi_remote_control_stop
      data:
        entity_id: vacuum.stofzuiger_boven