homeassistant:
  customize:
    sensor.ventilation_current_mode:
      hidden: true
  customize_glob:
    "switch.qubino_zmnhbdx_flush_2_relays*":
      hidden: true
    "sensor.qubino_zmnhbdx_flush_2_relays*":
      hidden: true

input_number:
  ventilation:
    name: Ventilatie
    initial: 1
    min: 1
    max: 3
    step: 1
    mode: slider
    icon: mdi:fan

sensor:
  - platform: template
    sensors:
      ventilation_current_mode:
        value_template: >
          {% if (is_state('switch.qubino_zmnhbdx_flush_2_relays_switch_2', 'on')) %}
            3.0
          {% elif (is_state('switch.qubino_zmnhbdx_flush_2_relays_switch_3', 'on')) %}
            2.0
          {% else %} 
            1.0
          {% endif %}

automation:
  - id: update_ventilation_slider
    alias: Ventilatie slider bijwerken
    trigger:
      platform: state
      entity_id: sensor.ventilation_current_mode
    condition:
      condition: template
      value_template: '{{ states.input_number.ventilation.state != states.sensor.ventilation_current_mode.state }}'
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.ventilation
        value: "{{ states.sensor.ventilation_current_mode.state }}"

  - id: ventilation_switches_1
    alias: Ventilatie switches 1
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_number.ventilation
        to: "1.0"
    condition:
      condition: template
      value_template: '{{ states.input_number.ventilation.state != states.sensor.ventilation_current_mode.state }}'
    action:
      - service: switch.turn_off
        entity_id: switch.qubino_zmnhbdx_flush_2_relays_switch_2
      - service: switch.turn_off
        entity_id: switch.qubino_zmnhbdx_flush_2_relays_switch_3

  - id: ventilation_switches_2
    alias: Ventilatie switches 2
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_number.ventilation
        to: "2.0"
    condition:
      condition: template
      value_template: '{{ states.input_number.ventilation.state != states.sensor.ventilation_current_mode.state }}'
    action:
      - service: switch.turn_off
        entity_id: switch.qubino_zmnhbdx_flush_2_relays_switch_2
      - service: switch.turn_on
        entity_id: switch.qubino_zmnhbdx_flush_2_relays_switch_3

  - id: ventilation_switches_3
    alias: Ventilatie switches 3
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_number.ventilation
        to: "3.0"
    condition:
      condition: template
      value_template: '{{ states.input_number.ventilation.state != states.sensor.ventilation_current_mode.state }}'
    action:
      - service: switch.turn_off
        entity_id: switch.qubino_zmnhbdx_flush_2_relays_switch_3
      - service: switch.turn_on
        entity_id: switch.qubino_zmnhbdx_flush_2_relays_switch_2

  - id: ventilation_bathroom_high
    alias: Ventileren badkamer (hoog)
    trigger:
      - platform: numeric_state
        entity_id: sensor.mold_sensor_bathroom
        above: 85
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.ventilation
        value: 3.0

  - id: ventilation_bathroom_medium
    alias: Ventileren badkamer (middel)
    trigger:
      - platform: numeric_state
        entity_id: sensor.mold_sensor_bathroom
        below: 85
        above: 75
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.ventilation
        value: 2.0

  - id: ventilation_bathroom_low
    alias: Ventileren badkamer (laag)
    trigger:
      - platform: numeric_state
        entity_id: sensor.mold_sensor_bathroom
        below: 75
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.ventilation
        value: 1.0
