input_select:
  ventilation_mode:
    name: Ventilatie
    options:
       - Auto
       - Uit
       - Laag
       - Midden
       - Hoog
    icon: mdi:fan

sensor:
  - platform: template
    sensors:
      ventilation_demand_bathroom:
        value_template: >
          {% if (is_state('binary_sensor.natural_ventilation_bathroom', 'on')) %}
            0
          {% elif (is_state('binary_sensor.high_humidity_bathroom', 'off')) %}
            0
          {% else %}
            3
          {% endif %}
      ventilation_demand_living_room_co2:
        value_template: >
          {% if (states('sensor.mhz19_co2') | int < 500) %}
            0
          {% elif (states('sensor.mhz19_co2') | int < 900) %}
            1
          {% elif (states('sensor.mhz19_co2') | int < 1500) %}
            2
          {% else %}
            3
          {% endif %}
      ventilation_demand:
        value_template: >
          {% if (is_state('input_select.ventilation_mode', 'Uit')) %}
            0
          {% elif (is_state('input_select.ventilation_mode', 'Laag')) %}
            1
          {% elif (is_state('input_select.ventilation_mode', 'Midden')) %}
            2
          {% elif (is_state('input_select.ventilation_mode', 'Hoog')) %}
            3
          {% else %}
            {{ [states('sensor.ventilation_demand_bathroom') | int, states('sensor.ventilation_demand_living_room_co2') | int] | max }}
          {% endif %}
      
      ventilation_current_mode:
        value_template: >
          {% if (is_state('switch.sonoff_ventilation_3', 'on')) %}
            3
          {% elif (is_state('switch.sonoff_ventilation_2', 'on')) %}
            2
          {% elif (is_state('switch.sonoff_ventilation_1', 'on')) %}
            1
          {% else %} 
            0
          {% endif %}

binary_sensor:
  - platform: template
    sensors:
      natural_ventilation_bathroom:
        value_template: >-
          {{ is_state('binary_sensor.0x00158d0001e481df', 'on') }}
        delay_on:
          seconds: 10
      high_humidity_bathroom:
        friendly_name: "Hoge luchtvochtigheid badkamer"
        value_template: >-
          {{ states('sensor.mold_sensor_bathroom')|int > 80 }}
        delay_off:
          minutes: 1
        delay_on:
          seconds: 5

automation:
  - id: ventilation_switches_0
    alias: Ventilatie switches 0
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.ventilation_demand
        to: "0"
    condition:
      condition: template
      value_template: '{{ states.sensor.ventilation_demand.state|int != states.sensor.ventilation_current_mode.state|int }}'
    action:
      - service: switch.turn_off
        entity_id: switch.sonoff_ventilation_3
      - service: switch.turn_off
        entity_id: switch.sonoff_ventilation_2
      - service: switch.turn_off
        entity_id: switch.sonoff_ventilation_1

  - id: ventilation_switches_1
    alias: Ventilatie switches 1
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.ventilation_demand
        to: "1"
    condition:
      condition: template
      value_template: '{{ states.sensor.ventilation_demand.state|int != states.sensor.ventilation_current_mode.state|int }}'
    action:
      - service: switch.turn_off
        entity_id: switch.sonoff_ventilation_2
      - service: switch.turn_off
        entity_id: switch.sonoff_ventilation_3
      - service: switch.turn_on
        entity_id: switch.sonoff_ventilation_1

  - id: ventilation_switches_2
    alias: Ventilatie switches 2
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.ventilation_demand
        to: "2"
    condition:
      condition: template
      value_template: '{{ states.sensor.ventilation_demand.state|int != states.sensor.ventilation_current_mode.state|int }}'
    action:
      - service: switch.turn_off
        entity_id: switch.sonoff_ventilation_3
      - service: switch.turn_on
        entity_id: switch.sonoff_ventilation_1
      - service: switch.turn_on
        entity_id: switch.sonoff_ventilation_2

  - id: ventilation_switches_3
    alias: Ventilatie switches 3
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.ventilation_demand
        to: "3"
    condition:
      condition: template
      value_template: '{{ states.sensor.ventilation_demand.state|int != states.sensor.ventilation_current_mode.state|int }}'
    action:
      - service: switch.turn_off
        entity_id: switch.sonoff_ventilation_2
      - service: switch.turn_on
        entity_id: switch.sonoff_ventilation_1
      - service: switch.turn_on
        entity_id: switch.sonoff_ventilation_3
