name: Check config

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install homeassistant
    - name: Check config
      run: |
        mv travis_secrets.yaml secrets.yaml
        hass --version
        hass -c . --script check_config
